### ISSUE TITLE
Dependencies not specified

### ISSUE THREAD

**Issue by mike-suggitt** [dataminr/expanded-react-test-utils#3]
All I get is a dist folder with a build file in it but the dependencies it needs aren't present

**Comment by ernieturner** [comment]
The dependencies for this project are declared within the bower.json and package.json file. How are you installing this library?

**Comment by ernieturner** [comment]
Please see the note on your other ticket (#4).

**Comment by mike-suggitt** [comment]
Please see comment in #4 for gratitude :)
