### ISSUE TITLE
Relies on requirejs

### ISSUE THREAD

**Issue by mike-suggitt** [dataminr/expanded-react-test-utils#4]
Uses requirejs but not specified anywhere.

**Comment by ernieturner** [comment]
I'm not sure what you mean by "not specified anywhere". What isn't specified? The dependency? The requireJS dependency is specified within the bower.json file. It would be very helpful when opening tickets if you could explain the problem in more detail.

**Comment by mike-suggitt** [comment]
Hi apologies yes I should mention that I npm'd it in rather than bower. Was referring to the package.json

-----Original Message-----

**Comment by ernieturner** [comment]
Ok, so I just pushed out a fairly large release (0.5.1) which updates this library a ton, including removing al requireJS deps and fully removing bower in favor of NPM. Give that a shot and hopefully you'll be more easily able to consume this library. Thanks!

**Comment by mike-suggitt** [comment]
@ernieturner That's really awesome thanks. Appreciate the effort and I've now switched libraries to  use your new release and it works great! :)
